artifacts/address.json
=> Add ropsten

docs/deployments/mainnet.md, docs/deployments/rinkeby.md, docs/deployments/ropsten.md
Fixes #263.
- reinstate 3 recent .md files so that external links don't break
- make the files simple & easy to maintain, while providing relevant info to people who would have arrived at them from external
=> Fix for #263 - broken links

README.md
Fixes #272. Make README to be more similar to that of ocean.js and ocean.py, wrt headings and emojis.
=> Issue 272 - improve README

docs/RELEASE_PROCESS.md
- Minor fix in the release process (update the git push command).
=> minor fix for the release process

README.md
Related issues https://github.com/oceanprotocol/multi-repo-issue/issues/83
- minor README.md update for the `usage section`.
=> updating the documentation for ocean-contracts usage

artifacts/address.json, migrations/2_deploy_contracts.js, package-lock.json, package.json, truffle.js
Closes #315
- deploy contracts on GAIA-X
- deploy contracts on Mumbai testnet
- add chainID to address.json  (manually so far)
- add startBlock to address.json  (manually so far)
=> add gaia-x & mumbai

artifacts/address.json, migrations/2_deploy_contracts.js, truffle.js
=> new moonbeamalpha deployment

artifacts/address.json, migrations/2_deploy_contracts.js, package.json, truffle.js
Ref: part of https://github.com/oceanprotocol/privateissues/issues/38
=> add catenaxpoa

contracts/interfaces/IERC20Template.sol, contracts/templates/ERC20Template.sol, contracts/templates/ERC20TemplateEnterprise.sol, test/unit/datatokens/ERC20Template.test.js, test/unit/datatokens/ERC20TemplateEnterprise.test.js
- Add getERC721Address function to ERC20 Templates
- Check OrderStarted event when doing startOrder
=> add getERC721Address to ERC20 Templates

contracts/interfaces/IDispenser.sol, contracts/interfaces/IERC20Template.sol, contracts/interfaces/IERC721Template.sol, contracts/interfaces/IFixedRateExchange.sol, contracts/interfaces/IPool.sol, contracts/interfaces/ISideStaking.sol, contracts/pools/balancer/BPool.sol, contracts/pools/dispenser/Dispenser.sol, contracts/pools/fixedRate/FixedRateExchange.sol, contracts/pools/ssContracts/SideStaking.sol, contracts/templates/ERC20Template.sol, contracts/templates/ERC20TemplateEnterprise.sol, contracts/templates/ERC721Template.sol, test/flow/Dispenser.test.js, test/flow/FixedRateExchange.test.js, test/flow/SideStaking.test.js, test/unit/datatokens/ERC721Template.test.js
Closes #458 
- make sure all contracts have a getId() function
PS: Artifacts & deployment are not included, will do that after several PRs
=> expose and test getId

contracts/interfaces/IFactoryRouter.sol, contracts/pools/FactoryRouter.sol, contracts/pools/balancer/BFactory.sol, test/flow/FixedRateExchange.test.js, test/flow/SwapFees.test.js, test/unit/pools/FactoryRouter.test.js
Closes #462 
Closes #463 
Breaking change:
FactoryRouter.updateOPFFee has changed
PS: Artifacts & deployment are not included, will do that after several PRs
=> refactor factory mappings & OPF Community Fees

.github/workflows/ci.yml
=> add docker build test

README.md
Fixes #608 
- Added NFT blogpost link
- Added SideStaking blogpost link
- Added Ocean Monetize blogpost link
- Added Fee docs link
- Removed vesting info
=> Added NFT, Fee, SideStaking and OceanMonetize links in the readme

scripts/deploy-contracts.js
=> additionalTokens

README.md
Removed 'Known issues' link and fix 'Development and testing' link
=> Minor fixes on the readme

addresses/address.json
Fixes #https://github.com/oceanprotocol/contracts/issues/667
- Replace lowercase addresses with checksum addresses in `address.json`
=> Replace lowercase addresses with checksum addresses

contracts/df/DFStrategyV1.sol, contracts/ve/veAllocate.sol, scripts/deploy-contracts.js
- Update `veAllocate` contract
=> Update veAllocate & DFStrategyV1 contracts

package-lock.json, package.json
=> bump hardhat components

.bumpversion.cfg, addresses/address.json, contracts/ve/veFeeEstimate.vy, package.json, scripts/deploy-contracts.js, scripts/deploy_ve_feeEstimate.js, setup.cfg
- deploy new veFeeEstimate
- update address.json
- update deploy scripts
- release v1.1.8
=> update feeEstimate & release

addresses/address.json
=> Remove moonbase

README.md
Fixes #722 .
- Fixed broken link
- Run linter 
-
=> Fixed fee structure broken link

addresses/address.json, hardhat.config.js, package-lock.json, package.json, scripts/deploy-contracts.js, setup.cfg
Add fvm testnet 
- network specs: https://github.com/filecoin-project/testnet-hyperspace#resources
- multisig: https://github.com/oceanprotocol/atlantic/blob/master/logs/wallets.md#filecoin-testnet-opfc-wallet
-
=> add filecoin fvm testnet 

.github/workflows/ci.yml, Dockerfile, scripts/deploy_docker.sh
Downgrade node version to 16, because of https://github.com/NomicFoundation/hardhat/issues/3877
- 
- 
-
=> downgrade to node 16

.bumpversion.cfg, addresses/address.json, package.json, setup.cfg
=> fix gen-x & release 1.1.14

contracts/pools/fixedRate/FixedRateExchange.sol, test/flow/FixedRateExchange.test.js
Closes #774 
- add  collectMarketFeeBatch
- add collectOceanFeeBatch
-
=> add batch collects

contracts/templates/ERC20Template3.sol
Closes #795 
- add roundSumStakes to TruevalSubmitted event
- 
-
=> expose agg predval after trueval

contracts/utils/PredictoorHelper.sol, scripts/deploy-contracts.js, test/unit/datatokens/ERC20Template3.test.js
Fixes #801
- Add `consumeMultiple` function into `PredictoorHelper` contract
- Function tests
=> Add `consumeMultiple` function into `PredictoorHelper` contract

.bumpversion.cfg, .github/workflows/ci.yml, Dockerfile, package.json, scripts/deploy_docker.sh, setup.cfg
=> fix docker

.github/workflows/ci.yml, Dockerfile, package.json, scripts/check_deployment.js
Fixes # .
- multistage build to optimize docker size
- barge deployment check
-
=> devops updates

contracts/templates/ERC20Template3.sol
- add new event, fired when paused state is changed
- 
-
=> Predictoor: track paused state using event

contracts/templates/ERC20Template3.sol, test/unit/datatokens/ERC20Template3.test.js
Fixes #811
-Update total stake amounts when a prediction gets updated.
=> Predictoor contract should update total stake amounts

contracts/templates/ERC20Template3.sol
Check if contract is paused and do not allow buyFrom
- 
- 
-
=> check if contract is paused at buy

.github/workflows/deployment_check.yml, scripts/deploy-contracts.js
=> Feature/send OCEAN in barge

addresses/address.json, scripts/deploy_vesting.js
- deploy Distributor contract
- deploy Vesting Wallet A
-
=> Deploy vesting A

.bumpversion.cfg, package-lock.json, package.json, scripts/deploy-contracts.js, setup.cfg
Fixes https://github.com/oceanprotocol/barge/issues/395
- remove hardcoded date for vesting0
- set endDate now + 1 year for vesting0
- release v2.0.4
=> remove hardcoded date

.bumpversion.cfg, .github/workflows/ci.yml, .solhint.json, addresses/address.json, hardhat.config.js, package-lock.json, package.json, scripts/deploy-contracts.js, setup.cfg
=> deploy on base
